version: "3"

services:
    broker:
        image: eclipse-mosquitto:1.6.5
        restart: always
        networks: 
            - mqtt
        ports:
            - 1883:1883
        command:
            ["mosquitto", "-v"]
    
    datastore:
        image: redis
        restart: always
        networks:
            - redis
        ports:
            - 6379:6379
        

    backend:
        build: ./services
        restart: always
        volumes:
            - nodered_data:/data
        networks:
            - mqtt
            - redis
        ports:
            - 1880:1880
        depends_on:
            - broker
            - datastore

networks:
    mqtt:
    redis:

volumes:
    nodered_data:
