version: "3"

services:
    broker:
        image: eclipse-mosquitto:1.6.5
        restart: always
        networks: 
            - mqtt
        ports:
            - 1883:1883
        command:
            ["mosquitto", "-v"]
    
    datastore:
        image: redis
        restart: always
        networks:
            - redis
        ports:
            - 6379:6379
        
    backend:
        build: ./services
        restart: always
        volumes:
            - nodered_data:/data
        networks:
            - mqtt
            - redis
            - telegram
            - decision
        ports:
            - 1880:1880
        depends_on:
            - broker
            - datastore
            - decision_layer

    telegram_layer:
        build: ./telegram-api
        restart: always
        networks: 
            - telegram
        environment: 
            - TELEGRAM_KEY=${TELEGRAM_KEY}
        depends_on: 
            - backend

    decision_layer:
        build: ./decision-making
        restart: always
        networks:
            - decision


networks:
    mqtt:
    redis:
    telegram:
    decision:

volumes:
    nodered_data:
